### PR TITLE
Fix/del error fix

### LINKED ISSUE #519: fix:511 is not compete,  how about the cmdDel part?
**What happend**:
pod could be nil in cmdDel..
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
https://github.com/intel/multus-cni/commit/fff8e490b964daf686de5cca9d421562e475af19

same reason with fix in cmdAdd part,  in cmdDel,  if getpod not working due to kclient acces,
pod is nil. then multus.go will panic, right?
**Anything else we need to know?**:
I think just add the code which #511 introduced to cmdDel()
**Environment**:

- Multus version 
  image path and image ID (from 'docker images')
- Kubernetes version (use `kubectl version`):
- Primary CNI for Kubernetes cluster:
- OS (e.g. from /etc/os-release):
- File of '/etc/cni/net.d/'
- File of '/etc/cni/multus/net.d'
- NetworkAttachment info (use `kubectl get net-attach-def -o yaml`)
- Target pod yaml info (with annotation, use `kubectl get pod <podname> -o yaml`)
- Other log outputs (if you use multus logging)

### PR DESCRIPTION
**Pull request by s1061123**
fix #519

### CODE REVIEW

File: multus/multus.go [hunk 1]
```diff
@@ -705,7 +705,24 @@ func cmdDel(args *skel.CmdArgs, exec invoke.Exec, kubeClient *k8s.ClientInfo) er
 	if kubeClient != nil {
```
Comment (amorenoz) [inline multus/multus.go:705]: Hi @s1061123 , I'm also hitting this issue.
Note that probably kubeClient  == nil
There is no call to k8s.GetK8sClient(in.Kubeconfig, kubeClient) in cmdDel. Maybe it should be added?

Comment (s1061123) [reply multus/multus.go:710]: Thank you for your comment! Yeah, I need to get kubeClient in cmdDel as well. I changed it.
