### PR TITLE
Make conflistDel() behave like conflistAdd()

### LINKED ISSUE #179: Chained meta plugin not found on Delete
Adding interface(s) with chained plugins (e.g. tuning) work fine.  When Deleting, the chained plugin cannot be found:

```
2018-10-30T14:40:33-04:00 [error] error in getting result from DelNetworkList: failed to find plugin "tuning" in path [/home/mcambria/go/src/github.com/containernetworking/bin]
2018-10-30T14:40:33-04:00 [error] Multus: error in invoke Conflist Del - "mcc-test1": error in getting result from DelNetworkList: failed to find plugin "tuning" in path [/home/mcambria/go/src/github.com/containernetworking/bin]
Multus: error in invoke Conflist Del - "mcc-test1": error in getting result from DelNetworkList: failed to find plugin "tuning" in path [/home/mcambria/go/src/github.com/containernetworking/bin]

```

It looks like logic was added to make this work for conflistAdd() by finding the plugin vis CNI_PATH:

https://github.com/intel/multus-cni/blame/bdf901c122f923d89fd88e15fb6dd79d8a98d4da/multus/multus.go#L126

Similar logic is missing for Delete.  Is there a reason?

When I add the same logic to conflistDel(), the problem goes away.   But does adding this break something else?

### PR DESCRIPTION
**Pull request by mccv1r0**
conflistAdd() finds binaries differently than conflistDel().
Make the two call find binaries the same way.

Fixes #179

Signed-off-by: Michael Cambria <mcambria@redhat.com>

### CODE REVIEW

File: multus/multus.go [hunk 1]
```diff
@@ -140,11 +140,13 @@ func conflistAdd(rt *libcni.RuntimeConf, rawnetconflist []byte, binDir string, e
 	return result, nil
 }
 
-func conflistDel(rt *libcni.RuntimeConf, rawnetconflist []byte, binDir string) error {
+//func conflistDel(rt *libcni.RuntimeConf, rawnetconflist []byte, binDir string) error {
```
Comment (s1061123) [inline multus/multus.go]: How about to remove it?

**Comment by s1061123** [comment]
merged, thanks again!
